### ISSUE TITLE
«shuı»

### ISSUE THREAD

**Issue by ciuak** [toaq/roots#36]
"shuı": {
      "official": {
        "english": "▯ is secret.",
        "gloss": "secret"
      },
      "frame": "0"
    }

@acotis framed this as a ‘0,’ but I'm pretty sure it should be a ‘c.’ Concrete things can too be kept away from view.

**Comment by acotis** [comment]
A type 0 slot does not need to be a proposition.  Slot types do not determine what type of argument can be given to the predicate, only how the predicate acts when it's the head of a serial.  (By the good design of the serial predicate system these two things often strongly correlate, but they are not the same thing.)

**Comment by ciuak** [comment]
> A type 0 slot does not need to be a proposition. Slot types do not determine what type of argument can be given to the predicate, only how the predicate acts when it's the head of a serial. (By the good design of the serial predicate system these two things often strongly correlate, but they are not the same thing.)

I'm pretty convinced, but I'd like @solpahi to confirm.

**Comment by acotis** [comment]
But I'm the one who invented them...

**Comment by ciuak** [comment]
Alright then. I'd still be glad to hear what solpahi has to say, though.
